name: py312aiwatermark
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - numpy
  - tqdm
  - loguru
  - click
  - pillow
  - opencv
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/nightly/cu126
      - torch
      - torchvision
      - torchaudio
      - huggingface-hub>=0.23.0
      - iopaint